### ISSUE TITLE
Not Sure Whats Wrong?

### ISSUE THREAD

**Issue by dr-NHA** [maybegreat48/GTA-V-Script-Decompiler#10]
Tried Decompiling abigail1_ysc\\abigail1.ysc.full
`
System.Exception: Return Expected
   at Decompiler.ScriptFile.AddFunction(Int32 start1, Int32 start2) in D:\a\GTA-V-Script-Decompiler\GTA-V-Script-Decompiler\GTA V Script Decompiler\ScriptFile.cs:line 200
   at Decompiler.ScriptFile.GetFunctions() in D:\a\GTA-V-Script-Decompiler\GTA-V-Script-Decompiler\GTA V Script Decompiler\ScriptFile.cs:line 277
   at Decompiler.ScriptFile.Decompile(ProgressBar bar) in D:\a\GTA-V-Script-Decompiler\GTA-V-Script-Decompiler\GTA V Script Decompiler\ScriptFile.cs:line 54
   at Decompiler.MainForm.openToolStripMenuItem_Click(Object sender, EventArgs e) in D:\a\GTA-V-Script-Decompiler\GTA-V-Script-Decompiler\GTA V Script Decompiler\MainForm.cs:line 104
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
`

Not Sure What U May Need Please Let Me Know :)

**Comment by FahQGrantRawlings** [comment]
What's wrong is these guys steal everything from other people and claim it as their own. Their scripts are as garbage as their Forza tool. These guys code backdoors and rats into everything they can.

**Comment by maybegreat48** [comment]
Are you compiling from source? The releases are outdated

**Comment by dr-NHA** [comment]
Yeah Compiled From Source And Still Not Working,
Ive Ended Up Using Sainan's As It Works 1000x Better And Gives Clean Dumps That Im Used To Seeing :)
